### ISSUE TITLE
Less Strict BPM Input? 

### ISSUE THREAD

**Issue by alexthescott** [alexthescott/Sprintify#26]
Allow for deleting of current value an inputing of a value +100 as demonstrated in the video below.

https://user-images.githubusercontent.com/43523995/204099257-06714002-bd01-43b3-ace4-d5a66bfbc105.mov

**Comment by Ykrej** [comment]
This flexibility sounds like a good idea just make sure to add an "isValid" state and maybe some sort of visual indicator of whether the defined range is valid. Will also need to update dependent forms(only PlaylistModal currently) to disable the submit button when isValid == false.

**Comment by alexthescott** [comment]
Closed https://github.com/alexthescott/Sprintify/pull/41
