### ISSUE TITLE
API Rate Limiting and Cacheing

### ISSUE THREAD

**Issue by Ykrej** [alexthescott/Sprintify#38]
API rate limiting errors(http 429) occurs when opening and closing playlist cards rapidly due to requesting track features.

When a 429 error occurs there is a retry-after response header containing the amount of time to wait before continuing making api calls.

Track features are static(atleast for short term) making this data good candidate for cacheing the data.

Rate limits dont seem to be a x calls/second, it is a moving window so rate limit should be handled as it occurs instead of avoided.
https://developer.spotify.com/documentation/web-api/guides/rate-limits/

**Comment by Ykrej** [comment]
Also need to figure out how to abort in progress callApi promises when closing the filterplaylist modal. Pass a cancelFlag into the promise that can be set from outer scope.

**Comment by alexthescott** [comment]
I'll let you decide if this issue can be closed after having [merged your rate_limiting branch](https://github.com/alexthescott/Sprintify/pull/39)
